2023-10-18 09:33:32,106 INFO    MainThread:256304 [wandb_setup.py:_flush():76] Current SDK version is 0.15.10
2023-10-18 09:33:32,107 INFO    MainThread:256304 [wandb_setup.py:_flush():76] Configure stats pid to 256304
2023-10-18 09:33:32,107 INFO    MainThread:256304 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sari\.config\wandb\settings
2023-10-18 09:33:32,107 INFO    MainThread:256304 [wandb_setup.py:_flush():76] Loading settings from C:\Users\sari\Desktop\DeepCover\wandb\settings
2023-10-18 09:33:32,108 INFO    MainThread:256304 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-18 09:33:32,108 INFO    MainThread:256304 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-18 09:33:32,108 INFO    MainThread:256304 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'C:\\Users\\sari\\Desktop\\DeepCover\\main.py'}
2023-10-18 09:33:32,109 INFO    MainThread:256304 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\sari\Desktop\DeepCover\wandb\run-20231018_093332-xseem2lo\logs\debug.log
2023-10-18 09:33:32,109 INFO    MainThread:256304 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\sari\Desktop\DeepCover\wandb\run-20231018_093332-xseem2lo\logs\debug-internal.log
2023-10-18 09:33:32,109 INFO    MainThread:256304 [wandb_init.py:init():564] calling init triggers
2023-10-18 09:33:32,109 INFO    MainThread:256304 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-10-18 09:33:32,109 INFO    MainThread:256304 [wandb_init.py:init():614] starting backend
2023-10-18 09:33:32,110 INFO    MainThread:256304 [wandb_init.py:init():618] setting up manager
2023-10-18 09:33:32,112 INFO    MainThread:256304 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-10-18 09:33:32,114 INFO    MainThread:256304 [wandb_init.py:init():624] backend started and connected
2023-10-18 09:33:32,117 INFO    MainThread:256304 [wandb_init.py:init():715] updated telemetry
2023-10-18 09:33:32,118 INFO    MainThread:256304 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2023-10-18 09:35:02,966 ERROR   MainThread:256304 [wandb_init.py:init():774] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-18 09:35:03,574 ERROR   MainThread:256304 [wandb_init.py:init():1183] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "C:\Users\sari\AppData\Local\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1165, in init
    run = wi.init()
  File "C:\Users\sari\AppData\Local\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 780, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-10-18 09:35:04,591 WARNING MsgRouterThr:256304 [router.py:message_loop():77] message_loop has been closed
